name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

env:
  PROJECT_ID: daily-ai-v2

jobs:
  deploy:
    name: Deploy Hosting (main and PR previews)
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # for Workload Identity Federation
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Install dependencies
        run: npm ci

      - name: Build (static export)
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ vars.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ vars.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ vars.NEXT_PUBLIC_FIREBASE_APP_ID }}
        run: npm run build

      - name: Deploy (PR preview channel)
        if: github.event_name == 'pull_request'
        env:
          CHANNEL_ID: pr-${{ github.event.number }}
        run: |
          firebase hosting:channel:deploy "$CHANNEL_ID" \
            --project "$PROJECT_ID" \
            --expires 7d \
            --non-interactive

      - name: Deploy (live)
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          firebase deploy --only hosting --project "$PROJECT_ID" --non-interactive --message "CI deploy $GITHUB_SHA"
